accounts/urls.py
from django.urls import path
from .views import Register, Login, Logout


app_name = 'accounts'


urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout')
]

djapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='products')),
]

products/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name='products'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('<int:id>/', ProductDetail.as_view(), name='detail')
]

accounts/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    pass

products/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=255, default='title of the product')
    description = models.TextField(blank=True, null=True)
    summary = models.TextField(null=True)
    price = models.DecimalField(max_digits=100000, decimal_places=2, default=100.00)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from .models import User

class UserloginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

accounts/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import login, logout, authenticate
from django.views import View
from django.core.exceptions import  ValidationError
from .models import User
from .forms import UserloginForm


class Register(View):
    template_name = 'accounts/register.html'

    def get(self,request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('products:list'))
        form = UserCreationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
        print(username, password, password2)
        qs = User.objects.filter(username__iexact=username)
        if qs.exists():
            raise  ValidationError('User with name username already exists')
        if password != password2:
            raise ValidationError('passwords must match')

        user = User(username=username)
        user.set_password(password)
        user.save()
        auth_user = authenticate(username=username, password=password)
        if auth_user is not None:
            login(request, auth_user)
            return HttpResponseRedirect(reverse('products:list'))
        return HttpResponseRedirect(reverse('accounts:login'))

class Login(View):
    template_name = 'accounts/login.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('products:list'))
        form = UserloginForm()
        return render(request, self.template_name, {'form':form})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('products:list'))
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('products:list'))
        raise ValidationError('Invalid credentials try again')

class Logout(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(reverse('accounts:login'))

    

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Product


class ProductList(View):
    template_name = 'products/list.html'

    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        return render(request, self.template_name, {'products': products})


class ProductDetail(View):
    template_name = 'products/detail.html'

    def get(self, request, id, *args, **kwargs):
        product = get_object_or_404(Product, pk=id)
        return render(request, self.template_name, {'product': product})

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    login
{% endblock  %}
{% block content %}
    <h3>Login</h3>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Login" />
        </form>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% block  title %}
    Register
{% endblock %}

{% block content %}
    <h3>Register</h3>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> Register </button>
    </form>
    
    
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Base |
       {% block title %} {% endblock %}

    </title>
</head>
<body>
    <div>
        <ul>
            <li><a href="{% url 'products:list' %}">home</a></li>
            <li><a href="{% url 'accounts:login' %}">login</a></li>
            <li><a href="{% url 'accounts:register' %}">register</a></li>
            <li><a href="{% url 'accounts:logout' %}">logout</a></li>
        </ul>
    </div>
    <div>
        {% block content %}
            <p>show something</p>
        {% endblock %}
    </div>
    
</body>
</html>

templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Detail
{% endblock %}
{% block content %}
    <div>
        <h4>{{ product.title }}</h4>
        <p>
            <small>{{ product.price }}</small>
        </p>
    </div>
{% endblock %}

templates/products/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    list
{% endblock %}
{% block content %}
    <h3>Product list</h3>
    {% if request.user.is_authenticated %}
        <small>You are authenticated</small>
    {% endif %}
    {% for product in products %}
        <div>
            <h3><a href="{% url 'products:detail' id=product.id %}">{{ product.title }}</a> </h3>
            
        </div>
    {% endfor %}

{% endblock %}